version: 0.2

phases:
  install:
    commands:
      - echo Install...
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash

  pre_build:
    commands:
      - echo Installing dependencies...
      - npm run install-client
      
  build:
    commands:
      - echo Testing...
      - cd client
      - npm run test
      - echo Building...
      - cd ..
      - npm run prod-build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: client/build